import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/common/Header";
import Footer from "./components/common/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
